sonar.projectKey=thec1rclehost123-cmd_minisocial_media
sonar.organization=thec1rclehost123-cmd
sonar.projectName=minisocial_media
sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
